### ISSUE TITLE
The recipe 'webrtc-audio-processing' fails at build step 'compile'

### ISSUE THREAD

**Issue by isometriq** [centricular/cerbero#5]
Did you had any trouble (and fix) with this recipe? 66/85
I'm on the "meson-1.10" branch.

Skipping the recipe is not an option i think since the good or bad plugins need it, and the whole package.
Retrying the step or the recipe does not work too.

Last error message is "libwebrtc_audio_processing_privatearch_la-aec_core_sse2.o: No such file or directory"
I can post my output if you want to see.

**Comment by nirbheek** [comment]
This happens because the path to the cerbero build directory is too long. @dashesy did try to warn you about that earlier. :)

To avoid this, you will need to move your cerbero directory somewhere else, like `C:/projects` instead of in the MinGW home directory. Unfortunately, this will mean that you will lose your build state.

As a workaround, for now you can skip the recipe. It is an optional dep anyway.

**Comment by nirbheek** [comment]
PS: Same issue occurs in upstream Cerbero, and the fix is probably to make webrtc-audio-processing not use Autotools.

**Comment by isometriq** [comment]
Oh ok, i didn't thought it was already this long :/
Yeah I hope skipping will do the trick.
If the final package requires it, I guess I would to remove the dependency somewhere

**Comment by nirbheek** [comment]
Closing because it's not specific to this branch and there's nothing we can really do about this...
